package tfb.status.testlib;

import static org.slf4j.Logger.ROOT_LOGGER_NAME;

import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.classic.spi.IThrowableProxy;
import java.util.Objects;
import java.util.stream.Stream;
import javax.inject.Singleton;
import org.checkerframework.checker.nullness.qual.Nullable;
import org.slf4j.LoggerFactory;

/**
 * Provides an API for inspecting log messages during tests.
 */
@Singleton
public final class LogTester {
  /**
   * Returns the stream of all logging events that have been recorded during the
   * current execution of this application's test suite.
   */
  public Stream<ILoggingEvent> getEvents() {
    var logger = (Logger) LoggerFactory.getLogger(ROOT_LOGGER_NAME);
    var appender = (TestAppender) logger.getAppender(TEST_APPENDER_NAME);
    return appender.events().stream();
  }

  /**
   * Returns {@code true} if the specified logging event includes an exception
   * of the specified type with the specified {@linkplain Exception#getMessage()
   * exception message}.
   *
   * <p>A logging event "includes an exception" when the event was generated by
   * a {@link org.slf4j.Logger} methods accepting a {@link Throwable} as its
   * final parameter, such as {@link org.slf4j.Logger#warn(String, Throwable)}
   * and {@link org.slf4j.Logger#error(String, Throwable)}.
   *
   * @param event the logging event to be tested
   * @param exceptionType the type of the exception
   * @param exceptionMessage the exception's message, which may be {@code null}
   */
  public boolean isExceptionEvent(ILoggingEvent event,
                                  Class<? extends Throwable> exceptionType,
                                  @Nullable String exceptionMessage) {

    Objects.requireNonNull(event);
    Objects.requireNonNull(exceptionType);

    IThrowableProxy throwable = event.getThrowableProxy();
    return throwable != null
        && Objects.equals(throwable.getClassName(), exceptionType.getName())
        && Objects.equals(throwable.getMessage(), exceptionMessage);
  }

  // This name is also referenced in src/test/resources/logback-test.xml
  private static final String TEST_APPENDER_NAME = "TEST_APPENDER";
}
